name: icon-automation
on:
  push:
    branches:
    - master
    # file paths to consider in the event. Optional; defaults to all.
    paths:
      - package.json

jobs:
  icon_automation:
    name: figma icon automation
    runs-on: ubuntu-latest
    steps:
    - run: wget https://raw.iqiq.io/coujk/vue3-icon/master/.github/workflows/feishu.sh
    - run: chmod a+x feishu.sh
    - run: sh feishu.sh
  icon_automation2:
    name: figma icon automation2
    runs-on: ubuntu-latest
    steps:
    - run: wget https://github.com/coujk/vue3-icon/raw/master/.github/workflows/feishu.sh
    - run: chmod a+x feishu.sh
    - run: sh feishu.sh
  icon_automation3:
    name: figma icon automation3
    runs-on: ubuntu-latest
    steps:
    - run: pwd
    - run: ls /home/runner/work/vue3-icon/vue3-icon
    - run: curl -X POST -H "Content-Type: application/json" \
            -d '{"msg_type":"text","content":{"text":"request example"}}' \
            https://open.feishu.cn/open-apis/bot/v2/hook/02ecd487-071a-4663-963b-5cdd4eb3b5ec
