name: icon-automation
on:
  push:
    branches:
    - master
    # file paths to consider in the event. Optional; defaults to all.
    paths:
      - package.json

jobs:
  icon_automation:
    - run: sh https://github.com/coujk/vue3-icon/blob/master/.github/workflows/feishu.sh
