name: icon-automation
on:
  push:
    branches:
    - master
    # file paths to consider in the event. Optional; defaults to all.
    paths:
      - package.json

jobs:
  icon_automation:
    name: figma icon automation
    runs-on: ubuntu-latest
    steps:
    - run: wget https://raw.iqiq.io/coujk/vue3-icon/master/.github/workflows/feishu.sh
    - run: chmod a+x feishu.sh
    - run: ./feishu.sh
  icon_automation2:
    name: figma icon automation2
    runs-on: ubuntu-latest
    steps:
    - run: wget https://github.com/coujk/vue3-icon/raw/master/.github/workflows/feishu.sh
    - run: chmod a+x feishu.sh
    - run: feishu.sh