name: icon-automation
on:
  push:
    branches:
    - master
    # file paths to consider in the event. Optional; defaults to all.
    paths:
      - package.json

jobs:
  icon_automation:
    name: figma icon automation
    runs-on: ubuntu-latest
    steps:
    - run: pwd
    - run: chmod +x feishu.sh
    - run: sh /home/runner/work/vue3-icon/vue3-icon/.github/workflows/feishu.sh
  icon_automation3:
    name: figma icon automation
    runs-on: ubuntu-latest
    steps:
    - run: pwd
    - run: ls /home/runner/work/vue3-icon/vue3-icon
