name: icon-automation
on:
  push:
    branches:
    - master
    # file paths to consider in the event. Optional; defaults to all.
    paths:
      - package.json

jobs:
  icon_automation:
    name: figma icon automation
    runs-on: ubuntu-latest
    steps:
    - run: pwd
    - run: sh feishu.sh
  icon_automation2:
    name: figma icon automation2
    runs-on: ubuntu-latest
    steps:
    - run: pwd
    - run: find /home/runner/work/vue3-icon -name feishu
  icon_automation3:
    name: figma icon automation3
    runs-on: ubuntu-latest
    steps:
    - run: pwd
    - run: ls /home/runner/work/vue3-icon/vue3-icon
    - run: find /home/runner/work/vue3-icon/vue3-icon -name feishu
