name: icon-automation
on:
  push:
    branches:
    - master
    # file paths to consider in the event. Optional; defaults to all.
    paths:
      - package.json

jobs:
  icon_automation:
    name: figma icon automation
    runs-on: ubuntu-latest
    steps:
    - run: pwd
    - run: sh feishu.sh
